Repository avinasdube/shareanalytics, pull requests merged in 2023-09, with the labels that each got.

#3 Add LICENSE
  LICENSE
Labels: documentation

#6 Yuno
  sa-server/config/dbconfig.js
  sa-server/controllers/authcontrol.js
  sa-server/index.js
  sa-server/models/authschema.js
  sa-server/package.json
  sa-server/routes/authroute.js
  sa-server/swagger.js
Labels: enhancement

#7 Navbar Frontend Done
  sa-client/src/assets/icons/logo-1.png
  sa-client/src/assets/icons/logo-2.png
  sa-client/src/components/organisms/Navbar/Navbar.scss
  sa-client/src/components/organisms/Navbar/Navbar.tsx
  sa-client/src/components/pages/Home/Home.scss
  sa-server/.gitignore
  sa-server/package-lock.json
Labels: enhancement

#11 #10 Login component done
  sa-client/public/index.html
  sa-client/src/App.scss
  sa-client/src/components/pages/Login/Login.scss
  sa-client/src/components/pages/Login/Login.tsx
Labels: enhancement

#12 Added a CONTRIBUTING.md File
  CONTRIBUTING.md
Labels: documentation, enhancement

#13 [CREATED]: Welcome page
  sa-client/src/components/pages/Home/Home.scss
  sa-client/src/components/pages/Home/Home.tsx
Labels: enhancement

#16 Dev
  sa-client/src/App.scss
  sa-client/src/components/organisms/Navbar/Navbar.scss
  sa-client/src/components/pages/Home/Home.scss
  sa-client/src/components/pages/Home/Home.tsx
  sa-client/src/components/pages/Login/Login.scss
  sa-client/src/components/pages/Login/Login.tsx
Labels: enhancement

#17 [new]: added new issue tempates and workflow
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, enhancement

#20 Updated README.md
  README.md
  sa-client/public/index.html
  sa-client/public/logo-1.png
  sa-client/public/manifest.json
  sa-client/public/robots.txt
Labels: documentation, enhancement

#22 Implemented MongoDB Atlas for Remote DB Access
  sa-client/package-lock.json
  sa-client/package.json
  sa-client/src/utils/sampleSignup.tsx
  sa-server/.env
  sa-server/.env.example
  sa-server/.gitignore
  sa-server/config/dbconfig.js
  sa-server/controllers/authcontrol.js
  sa-server/index.js
  sa-server/models/authschema.js
  sa-server/routes/authroute.js
Labels: documentation, enhancement, feature
